"""Safe, read-only Nexus telemetry monitor utilities."""

from .anomaly_detector import (
    DetectionResult,
    GPUReading,
    MLWeights,
    TelemetrySnapshot,
    detect_anomalies,
    invoke_ml_predictive_repair,
)
from .monsterball import (
    MONSTERBALL_WEIGHTS,
    MatchSnapshot,
    PlayerStats,
    PredictionResult,
    PredictorWeights,
    predict,
    predict_player,
    rank_players,
    render_match_report,
)
from .super_logical import (
    LOGICAL_CAPACITY,
    MONSTERBALL_SUPER_WEIGHTS,
    TOKEN_SUPER_WEIGHTS,
    UNIVERSAL_SUPER_WEIGHTS,
    LogicalReading,
    SuperLogicalResult,
    SuperLogicalWeights,
    compose_super_predict,
    render_super_logical_report,
    super_predict,
)
from .algebra3 import (
    ALGEBRA3_VERSION,
    BEHAVIOR_PROFILES,
    MONSTERBALL_A3_WEIGHTS,
    HUMAN_RESPONSE_A3_WEIGHTS,
    TOKEN_A3_WEIGHTS,
    UNIVERSAL_A3_WEIGHTS,
    Algebra3Result,
    Algebra3Weights,
    BehaviorProfile,
    apply_algebra3,
    match_behavior,
    render_algebra3_report,
)

__all__ = [
    # anomaly_detector
    "DetectionResult",
    "GPUReading",
    "MLWeights",
    "TelemetrySnapshot",
    "detect_anomalies",
    "invoke_ml_predictive_repair",
    # monsterball
    "MONSTERBALL_WEIGHTS",
    "MatchSnapshot",
    "PlayerStats",
    "PredictionResult",
    "PredictorWeights",
    "predict",
    "predict_player",
    "rank_players",
    "render_match_report",
    # super_logical
    "LOGICAL_CAPACITY",
    "MONSTERBALL_SUPER_WEIGHTS",
    "TOKEN_SUPER_WEIGHTS",
    "UNIVERSAL_SUPER_WEIGHTS",
    "LogicalReading",
    "SuperLogicalResult",
    "SuperLogicalWeights",
    "compose_super_predict",
    "render_super_logical_report",
    "super_predict",
    # algebra3
    "ALGEBRA3_VERSION",
    "BEHAVIOR_PROFILES",
    "MONSTERBALL_A3_WEIGHTS",
    "HUMAN_RESPONSE_A3_WEIGHTS",
    "TOKEN_A3_WEIGHTS",
    "UNIVERSAL_A3_WEIGHTS",
    "Algebra3Result",
    "Algebra3Weights",
    "BehaviorProfile",
    "apply_algebra3",
    "match_behavior",
    "render_algebra3_report",
]
